server:
  port: 8831

spring:

  ai:
    openai:
#      Key分享自：https://pgthinker.me/2023/10/03/196/
      api-key: sk-KgvugzpKzki15GFxB72e7782De844b23B3E4Fc6dDf40B29a
      base-url: https://api.mnzdna.xyz
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/demo