server:
  port: 8898


spring:
  ai:
    openai:
      api-key: sk-zk2503axxxxxxxxxxxxcf6613f975d2750

      base-url: https://flag.example.com
  mvc:
    view:
      prefix: classpath:/static/
      suffix: .html